name: FINAL-BUILD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
      - name: Build APK
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          command: android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ABU-NJM-FINAL
          path: bin/*.apk
